imports:
    - { resource: security.yml }
# SymfonyFrameworkBundle Configuration
framework:
    secret:          pleaseChangeMe!pleaseChangeMe!
    router:
        resource: "%kernel.root_dir%/configs/symfony/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] }
    trusted_proxies: ~
    session:
        storage_id: newscoop_newscoop.session.storage
        handler_id: ~
    fragments: ~
    translator: { fallback: en }
    http_method_override: true

monolog:
    channels: ["sentry"]
    handlers:
        sentry:
            type:  raven
            dsn:   'http://9cd083992bcc4dbba05b6a0253b30b3b:57ae69b9ea7347c1bca8583ab1e3da5f@sentry.sourcefabric.org/5'
            level: notice
            channels: ['sentry']

doctrine:
    dbal:
        charset: UTF8
        types:
            point: Newscoop\NewscoopBundle\ORM\PointType
    orm:
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false

# FOSRestBundle Configuration
fos_rest:
    allowed_methods_listener: true
    routing_loader:
        default_format: ~
    view:
        default_engine: twig
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.sourcefabric-org.newscoop+json']
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener:
        default_priorities:
            - json
            - html
        fallback_format: json
        prefer_extension: true
    exception:
        codes:
            'Newscoop\Exception\ResourcesConflictException': 409
            'Newscoop\Exception\InvalidParametersException': 422
            'Newscoop\Exception\ResourceIsEmptyException': 200
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\EntityNotFoundException': 404
            'Symfony\Component\Form\Exception\InvalidArgumentException': 500
            'Symfony\Component\HttpKernel\Exception\FlattenException': 404
            'Symfony\Component\Routing\Exception\MethodNotAllowedException': 404
            'Newscoop\Exception\ResourceNotModifiedException': 304
            'Newscoop\NewscoopException': 500
            'OAuth2\OAuth2AuthenticateException': 401
        messages:
            'Newscoop\Exception\ResourcesConflictException': true
            'Newscoop\Exception\InvalidParametersException': true
            'Newscoop\Exception\ResourceIsEmptyException': true
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Doctrine\ORM\EntityNotFoundException': true
            'Symfony\Component\Form\Exception\InvalidArgumentException' : true
            'Symfony\Component\Routing\Exception\MethodNotAllowedException': true
            'Symfony\Component\HttpKernel\Exception\FlattenException': true
            'Newscoop\Exception\ResourceNotModifiedException': false
            'OAuth2\OAuth2AuthenticateException': true
            'Newscoop\NewscoopException': true

fos_oauth_server:
    service:
        options:
            supported_scopes: standard_access
        user_provider: user.manager
    db_driver: orm
    client_class:        Newscoop\GimmeBundle\Entity\Client
    access_token_class:  Newscoop\GimmeBundle\Entity\AccessToken
    refresh_token_class: Newscoop\GimmeBundle\Entity\RefreshToken
    auth_code_class:     Newscoop\GimmeBundle\Entity\AuthCode

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            Newscoop:
                namespace_prefix: Newscoop\Entity
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            NewscoopBundle:
                namespace_prefix: Newscoop\NewscoopBundle\Entity
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_Comment:
                namespace_prefix: Newscoop\Entity\Comment
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_Package:
                namespace_prefix: Newscoop\Package
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_Image:
                namespace_prefix: Newscoop\Image
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_Snippet:
                namespace_prefix: Newscoop\Entity\Snippet
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_SnippetTemplate:
                namespace_prefix: Newscoop\Entity\Snippet\SnippetTemplate
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"
            Newscoop_Articles:
                namespace_prefix: Newscoop\ArticlesBundle\Entity
                path: "@NewscoopGimmeBundle/Resources/config/serializer/newscoop"


# SensioExtraBundle Configuration
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'Newscoop\GimmeBundle\Controller\ExceptionController::showAction'

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: knp_page                # page query parameter name
        sort_field_name: knp_sort          # sort field query parameter name
        sort_direction_name: knp_direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

newscoop_gimme:
    allow_origin:
        - "*"

bazinga_js_translation:
    locale_fallback: en

nelmio_api_doc:
    name:                     Newscoop REST API documentation
    request_listener:
        enabled:              false

ewz_recaptcha:
    public_key:
    private_key:
    enabled: true
    locale_key: kernel.default_locale

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            sluggable: false
            translatable: true
            sortable: false
            loggable: false
