admin_login:
    pattern:   /admin/login
    defaults:  { _controller: NewscoopNewscoopBundle:Security:login }
admin_login_check:
    pattern:   /admin/login_check
admin_logout:
    pattern:   /admin/logout{php}
    defaults: { php: ".php" }
fos_js_routing:
    prefix: /admin
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_bazinga_jstranslation:
    prefix: /admin
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    options:
        expose: true
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    options:
        expose: true
oauth_login:
    pattern:   /oauth/v2/auth_login
    defaults:  { _controller: NewscoopGimmeBundle:Oauth:login }
oauth_login_check:
    pattern:   /oauth/v2/auth_login_check
gimme:
    type: rest
    prefix: /api
    resource: "@NewscoopGimmeBundle/Resources/config/routing.yml"
admin_login_check:
    pattern:   /admin/login_check
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation/rest-api
NewscoopGimmeBundleConfigureApi:
    resource: "@NewscoopGimmeBundle/Controller/ConfigureApiController.php"
    prefix:   /
    type:     annotation
newscoop:
    prefix: /
    resource: "@NewscoopNewscoopBundle/Resources/config/routing.yml"
articles:
    prefix: /
    resource: "@NewscoopArticlesBundle/Resources/config/routing.yml"
plugins:
    resource: .
    type: plugins
zendBridge:
    prefix: /
    resource: "@NewscoopZendBridgeBundle/Resources/config/routing.yml"